# Generated by Django 4.1.5 on 2023-01-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numdos', models.CharField(max_length=255, verbose_name='NUMDOS')),
                ('numdosverling', models.CharField(max_length=255, verbose_name='NUMDOSVERLING')),
                ('ancart', models.CharField(max_length=255, verbose_name='ANCART')),
                ('filiere', models.CharField(max_length=255, verbose_name='FILIERE')),
                ('etape', models.FloatField(verbose_name='ETAPE')),
                ('verling', models.CharField(max_length=255, verbose_name='VERLING')),
                ('formats', models.CharField(max_length=255, verbose_name='FORMAT')),
            ],
        ),
    ]
